---
- hosts: "{{ host }}"
  become: true
  pre_tasks:
    - import_tasks: validation.yml
  vars:
    mount_path: "/opt/{{ admin }}/users/{{ mount_user }}/sites/{{ mount_source_site }}-mnt"
    mount_path_sshfs: "/sites/{{ mount_source_site }}"
  tasks:
    - name: "mount/provision : create mount folder"
      file:
        state: directory
        path: "{{ mount_path }}"
        owner: "{{ mount_user }}"
        group: "{{ mount_user }}"
        mode: "0750"

    - name: "mount/provision : create fstab entry for site mount '{{ mount_source_site }}' to user '{{ mount_user }}'"
      mount:
        path: "{{ mount_path }}"
        src: "{{ mount_source_user }}@{{ mount_source_host }}:{{ mount_path_sshfs }}"
        fstype: fuse.sshfs
        opts: "noauto,user,identityfile=/home/{{ mount_user }}/.ssh/id_rsa,defaults,_netdev,follow_symlinks"
        state: present
