version: "3.3"

services:
  test-web:
    image: sitepilot/autopilot-test:20.04
    container_name: test-server
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8222:22"
      - "8080:80"
      - "8443:443"
      - "8070:7080"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

