---
- name: "backup : validate input"
  assert:
    that:
      - backup_s3_key is defined
      - backup_s3_secret is defined
      - backup_s3_bucket is defined
      - backup_password is defined
      - backup_tags is defined
      - backup_path is defined or backup_database_name is defined
