---
- name: "base : install required packages"
  apt:
    pkg:
      - software-properties-common
      - ca-certificates
      - build-essential
      - curl
      - python3
      - python3-pip
      - python3-setuptools
      - unattended-upgrades
      - zip
      - unzip
      - acl
      - zsh
      - ncdu
      - gnupg
      - cron
      - nano
      - ntpdate
      - rsyslog
    state: present
    update_cache: yes

- name: "base : enable and start rsyslog"
  service:
    name: rsyslog
    state: started
    enabled: true

- name: "base : ensure 'isolated' group exists"
  group:
    name: "isolated"
    state: present

- name: "base : prepare filesystem"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ root_path }}"
      mode: "0755"
      owner: "root"
    - path: "{{ root_path }}/users"
      mode: "0755"
      owner: "root"
