---
- name: "firewall : install required packages"
  apt:
    name: "ufw"
    state: present

- name: "firewall : create firewall rules"
  ufw:
    port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    rule: allow
    state: "{{ firewall_state }}"
  loop: "{{ firewall_rules }}"
  when: firewall_rules is defined
