---
- include: upgrade.yml
  tags: "upgrade"

- include: base.yml
  tags: "base"

- include: sshd.yml
  tags: "sshd"

- include: config.yml
  tags: "config"

- include: admin.yml
  tags: "admin"

- include: firewall.yml
  tags: "firewall"

- include: lshttpd.yml
  tags: "lshttpd"

- include: lsphp73.yml
  tags: "lsphp73"

- include: lsphp74.yml
  tags: "lsphp74"

- include: caddy.yml
  tags: "caddy"

- include: composer.yml
  tags: "composer"

- include: nodejs.yml
  tags: "nodejs"

- include: supervisor.yml
  tags: "supervisor"

- include: restic.yml
  tags: "restic"

- include: swap.yml
  tags: "swap"

# ----- Optional ----- #

- include: msmtp.yml
  tags: "msmtp"
  when: install_smtp | bool

- include: mysql.yml
  tags: "mysql"
  when: install_mysql | bool

- include: redis.yml
  tags: "redis"
  when: install_redis | bool

- include: fail2ban.yml
  tags: "fail2ban"
  when: install_fail2ban | bool

- include: node-exporter.yml
  tags: "node-exporter"
  when: install_node_exporter | bool

- include: phpmyadmin.yml
  tags: "phpmyadmin"
  when: install_phpmyadmin | bool

- include: docker.yml
  tags: "docker"
  when: install_docker | bool

- include: wpcli.yml
  tags: "wpcli"
  when: install_wpcli | bool

- include: wordmove.yml
  tags: "wordmove"
  when: install_wordmove | bool

- include: unattended-upgrades.yml
  tags: "unattended-upgrades"
  when: install_unattended_upgrades | bool
