---
- name: "phpmyadmin : create service folders"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ root_path }}/services"
      mode: "0700"
      owner: "root"
    - path: "{{ root_path }}/services/phpmyadmin"
      mode: "0700"
      owner: "root"

- name: "phpmyadmin : generate Docker Compose configuration"
  template:
    src: phpmyadmin_docker_compose.j2
    dest: "{{ root_path }}/services/phpmyadmin/docker-compose.yml"
    mode: "0600"

- name: "phpmyadmin : start containers"
  docker_compose:
    project_src: "{{ root_path }}/services/phpmyadmin"
