---
- name: "redis : create service folders"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - path: /opt/sitepilot/services
      mode: "0700"
      owner: "root"
    - path: /opt/sitepilot/services/redis
      mode: "0700"
      owner: "root"
    - path: /opt/sitepilot/services/redis/data
      mode: "0700"
      owner: "1001"

- name: "redis : generate Docker Compose configuration"
  template:
    src: redis_docker_compose.j2
    dest: /opt/sitepilot/services/redis/docker-compose.yml
    mode: "0600"

- name: "redis : start containers"
  docker_compose:
    project_src: /opt/sitepilot/services/redis
