---
- name: "wordmove : install packages"
  apt:
    pkg:
      - rubygems
      - rsync
    state: present
    update_cache: no

- name: "wordmove : install wordmove gem for all users"
  gem:
    name: wordmove
    state: latest
    user_install: no
    include_dependencies: yes
    force: yes
