---
- hosts: "all"
  become: true
  pre_tasks:
    - import_tasks: validation.yml
  vars:
    site_path: "{{ root_path }}/users/{{ site_user }}/sites/{{ site_name }}"
    site_path_vhost: "/usr/local/lsws/conf/vhosts/{{ site_name }}.conf"
    site_path_proxy: "/etc/caddy/vhosts/{{ site_name }}.conf"
    site_path_fail2ban: "/etc/fail2ban/jail.d/{{ site_name }}.conf"
  tasks:
    - name: "site/destroy : {{ site_user }} : {{ site_name }} : remove site folder"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ site_path }}"

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : remove vhost configuration"
      file:
        path: "{{ site_path_vhost }}"
        state: absent

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : remove proxy configuration"
      file:
        path: "{{ site_path_proxy }}"
        state: absent

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : remove fail2ban configuration"
      file:
        path: "{{ site_path_fail2ban }}"
        state: absent

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : reload web server"
      service:
        name: lshttpd
        state: reloaded

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : reload proxy server"
      service:
        name: caddy
        state: reloaded

    - name: "site/destroy : {{ site_user }} : {{ site_name }} : reload fail2ban"
      service:
        name: fail2ban
        state: reloaded
      when: install_fail2ban | bool
