---
- hosts: "{{ host }}"
  become: true
  pre_tasks:
    - import_tasks: validation.yml
  vars:
    site_backends:
      - 127.0.0.1
    site_path: "/opt/{{ admin }}/users/{{ site_user }}/sites/{{ site_name }}"
    site_path_vhost: "/usr/local/lsws/conf/vhosts/{{ site_name }}.conf"
    site_path_proxy: "/etc/caddy/vhosts/{{ site_name }}.conf"
    site_path_fail2ban: "/etc/fail2ban/jail.d/{{ site_name }}.conf"
  tasks:
    - name: "site/provision : {{ site_user }} : {{ site_name }} : create folders"
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: "{{ item.mode }}"
      loop:
        - path: "{{ site_path }}"
          owner: "{{ site_user }}"
          mode: "0750"
        - path: "{{ site_path }}/public"
          owner: "{{ site_user }}"
          mode: "0750"
        - path: "{{ site_path }}/logs"
          owner: "{{ site_user }}"
          mode: "0750"

    - name: "site/provision : {{ site_user }} : {{ site_name }} : generate vhost configuration"
      template:
        src: ./templates/lshttpd_vhost.j2
        dest: "{{ site_path_vhost }}"
        owner: "lsadm"
        group: "nogroup"
        mode: "0644"

    - name: "site/provision : {{ site_user }} : {{ site_name }} : generate proxy vhost"
      template:
        src: ./templates/caddy_proxy_vhost.j2
        dest: "{{ site_path_proxy }}"
        owner: "caddy"
        group: "caddy"
        mode: "0644"

    - name: "site/provision : {{ site_user }} : {{ site_name }} : generate fail2ban jail"
      template:
        src: ./templates/fail2ban_jail.j2
        dest: "{{ site_path_fail2ban }}"
        owner: "root"
        group: "root"
        mode: "0644"
      when: install_fail2ban | bool

    - name: "site/provision : {{ site_user }} : {{ site_name }} : reload web server"
      service:
        name: lshttpd
        state: restarted

    - name: "site/provision : {{ site_user }} : {{ site_name }} : reload proxy server"
      service:
        name: caddy
        state: reloaded

    - name: "site/provision : {{ site_user }} : {{ site_name }} : reload fail2ban"
      service:
        name: fail2ban
        state: reloaded
      when: install_fail2ban | bool
