---
- hosts: "all"
  become: true
  pre_tasks:
    - name: "site/provision : validate input"
      assert:
        that: 
          - admin | length > 3
          - admin | length < 32
          - user | length > 3
          - user | length < 32
          - site | length > 3 
          - site | length < 32
          - php_version == 74 or php_version == 73
          - domains is defined
  vars:
    backends:
      - 127.0.0.1
    path: "/opt/{{ admin }}/users/{{ user }}/sites/{{ site }}"
    path_vhost: "/usr/local/lsws/conf/vhosts/{{ site }}.conf"
    path_proxy: "/etc/caddy/vhosts/{{ site }}.conf"
    path_fail2ban: "/etc/fail2ban/jail.d/{{ site }}.conf"
  tasks:
    - name: "site/provision : {{ user }} : {{ site }} : create folders"
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: "{{ item.mode }}"
      loop:
        - path: "{{ path }}"
          owner: "{{ user }}"
          mode: "0750"
        - path: "{{ path }}/public"
          owner: "{{ user }}"
          mode: "0750"
        - path: "{{ path }}/logs"
          owner: "{{ user }}"
          mode: "0750"

    - name: "site/provision : {{ user }} : {{ site }} : generate vhost configuration"
      template:
        src: ./templates/lshttpd_vhost.j2
        dest: "{{ path_vhost }}"
        owner: "lsadm"
        group: "nogroup"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : generate proxy vhost"
      template:
        src: ./templates/caddy_proxy_vhost.j2
        dest: "{{ path_proxy }}"
        owner: "caddy"
        group: "caddy"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : generate fail2ban jail"
      template:
        src: ./templates/fail2ban_jail.j2
        dest: "{{ path_fail2ban }}"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : reload web server"
      service:
        name: lshttpd
        state: restarted

    - name: "site/provision : {{ user }} : {{ site }} : reload proxy server"
      service:
        name: caddy
        state: reloaded

    - name: "site/provision : {{ user }} : {{ site }} : reload fail2ban"
      service:
        name: fail2ban
        state: reloaded
